[project]
name = "minio-operator-ext"
version = "0.0.0"
dependencies = [
    "click",
    "kopf",
    "kubernetes",
    "minio",
    "pydantic",
    "python-dotenv",
    "uvloop"
]

[project.optional-dependencies]
dev = []

[project.scripts]
minio-operator-ext = "minio_operator_ext.cli:main"

[tool.setuptools.packages.find]
include = ["minio_operator_ext"]
