apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: minio-tenant
spec: {}
status: {}
---
# Source: tenant/templates/tenant-configuration.yaml
apiVersion: v1
kind: Secret
metadata:
  name: myminio-env-configuration
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
---
# Source: tenant/templates/tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
spec:
  image: "quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z"
  imagePullPolicy: IfNotPresent
  ## Secret with default environment variable configurations
  configuration:
    name: myminio-env-configuration
  pools:
    - servers: 1
      name: default
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
  mountPath: /export
  subPath: /data
  requestAutoCert: true
  features:
    bucketDNS: false
    enableSFTP: false
  podManagementPolicy: Parallel
  prometheusOperator: false
