//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucket) DeepCopyInto(out *MinioBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucket.
func (in *MinioBucket) DeepCopy() *MinioBucket {
	if in == nil {
		return nil
	}
	out := new(MinioBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleAbortIncompleteMultipartUpload) DeepCopyInto(out *MinioBucketLifecycleAbortIncompleteMultipartUpload) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleAbortIncompleteMultipartUpload.
func (in *MinioBucketLifecycleAbortIncompleteMultipartUpload) DeepCopy() *MinioBucketLifecycleAbortIncompleteMultipartUpload {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleAbortIncompleteMultipartUpload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleAnd) DeepCopyInto(out *MinioBucketLifecycleAnd) {
	*out = *in
	out.XMLName = in.XMLName
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]MinioBucketLifecycleTag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleAnd.
func (in *MinioBucketLifecycleAnd) DeepCopy() *MinioBucketLifecycleAnd {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleAnd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleConfiguration) DeepCopyInto(out *MinioBucketLifecycleConfiguration) {
	*out = *in
	out.XMLName = in.XMLName
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MinioBucketLifecycleRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleConfiguration.
func (in *MinioBucketLifecycleConfiguration) DeepCopy() *MinioBucketLifecycleConfiguration {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleDelMarkerExpiration) DeepCopyInto(out *MinioBucketLifecycleDelMarkerExpiration) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleDelMarkerExpiration.
func (in *MinioBucketLifecycleDelMarkerExpiration) DeepCopy() *MinioBucketLifecycleDelMarkerExpiration {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleDelMarkerExpiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleExpiration) DeepCopyInto(out *MinioBucketLifecycleExpiration) {
	*out = *in
	out.XMLName = in.XMLName
	in.Date.DeepCopyInto(&out.Date)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleExpiration.
func (in *MinioBucketLifecycleExpiration) DeepCopy() *MinioBucketLifecycleExpiration {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleExpiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleFilter) DeepCopyInto(out *MinioBucketLifecycleFilter) {
	*out = *in
	out.XMLName = in.XMLName
	in.And.DeepCopyInto(&out.And)
	out.Tag = in.Tag
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleFilter.
func (in *MinioBucketLifecycleFilter) DeepCopy() *MinioBucketLifecycleFilter {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleNoncurrentVersionExpiration) DeepCopyInto(out *MinioBucketLifecycleNoncurrentVersionExpiration) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleNoncurrentVersionExpiration.
func (in *MinioBucketLifecycleNoncurrentVersionExpiration) DeepCopy() *MinioBucketLifecycleNoncurrentVersionExpiration {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleNoncurrentVersionExpiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleNoncurrentVersionTransition) DeepCopyInto(out *MinioBucketLifecycleNoncurrentVersionTransition) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleNoncurrentVersionTransition.
func (in *MinioBucketLifecycleNoncurrentVersionTransition) DeepCopy() *MinioBucketLifecycleNoncurrentVersionTransition {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleNoncurrentVersionTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleRule) DeepCopyInto(out *MinioBucketLifecycleRule) {
	*out = *in
	out.XMLName = in.XMLName
	out.AbortIncompleteMultipartUpload = in.AbortIncompleteMultipartUpload
	in.Expiration.DeepCopyInto(&out.Expiration)
	out.DelMarkerExpiration = in.DelMarkerExpiration
	in.RuleFilter.DeepCopyInto(&out.RuleFilter)
	out.NoncurrentVersionExpiration = in.NoncurrentVersionExpiration
	out.NoncurrentVersionTransition = in.NoncurrentVersionTransition
	in.Transition.DeepCopyInto(&out.Transition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleRule.
func (in *MinioBucketLifecycleRule) DeepCopy() *MinioBucketLifecycleRule {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleTag) DeepCopyInto(out *MinioBucketLifecycleTag) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleTag.
func (in *MinioBucketLifecycleTag) DeepCopy() *MinioBucketLifecycleTag {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketLifecycleTransition) DeepCopyInto(out *MinioBucketLifecycleTransition) {
	*out = *in
	out.XMLName = in.XMLName
	in.Date.DeepCopyInto(&out.Date)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketLifecycleTransition.
func (in *MinioBucketLifecycleTransition) DeepCopy() *MinioBucketLifecycleTransition {
	if in == nil {
		return nil
	}
	out := new(MinioBucketLifecycleTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketList) DeepCopyInto(out *MinioBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketList.
func (in *MinioBucketList) DeepCopy() *MinioBucketList {
	if in == nil {
		return nil
	}
	out := new(MinioBucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketSpec) DeepCopyInto(out *MinioBucketSpec) {
	*out = *in
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(MinioBucketLifecycleConfiguration)
		(*in).DeepCopyInto(*out)
	}
	out.TenantRef = in.TenantRef
	if in.Versioning != nil {
		in, out := &in.Versioning, &out.Versioning
		*out = new(MinioBucketVersioningConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketSpec.
func (in *MinioBucketSpec) DeepCopy() *MinioBucketSpec {
	if in == nil {
		return nil
	}
	out := new(MinioBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketStatus) DeepCopyInto(out *MinioBucketStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioBucketSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketStatus.
func (in *MinioBucketStatus) DeepCopy() *MinioBucketStatus {
	if in == nil {
		return nil
	}
	out := new(MinioBucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketVersioningConfiguration) DeepCopyInto(out *MinioBucketVersioningConfiguration) {
	*out = *in
	out.XMLName = in.XMLName
	if in.ExcludedPrefixes != nil {
		in, out := &in.ExcludedPrefixes, &out.ExcludedPrefixes
		*out = make([]MinioBucketVersioningExcludedPrefix, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketVersioningConfiguration.
func (in *MinioBucketVersioningConfiguration) DeepCopy() *MinioBucketVersioningConfiguration {
	if in == nil {
		return nil
	}
	out := new(MinioBucketVersioningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketVersioningExcludedPrefix) DeepCopyInto(out *MinioBucketVersioningExcludedPrefix) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketVersioningExcludedPrefix.
func (in *MinioBucketVersioningExcludedPrefix) DeepCopy() *MinioBucketVersioningExcludedPrefix {
	if in == nil {
		return nil
	}
	out := new(MinioBucketVersioningExcludedPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroup) DeepCopyInto(out *MinioGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroup.
func (in *MinioGroup) DeepCopy() *MinioGroup {
	if in == nil {
		return nil
	}
	out := new(MinioGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBinding) DeepCopyInto(out *MinioGroupBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBinding.
func (in *MinioGroupBinding) DeepCopy() *MinioGroupBinding {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroupBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBindingList) DeepCopyInto(out *MinioGroupBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioGroupBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBindingList.
func (in *MinioGroupBindingList) DeepCopy() *MinioGroupBindingList {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroupBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBindingSpec) DeepCopyInto(out *MinioGroupBindingSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBindingSpec.
func (in *MinioGroupBindingSpec) DeepCopy() *MinioGroupBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBindingStatus) DeepCopyInto(out *MinioGroupBindingStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioGroupBindingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBindingStatus.
func (in *MinioGroupBindingStatus) DeepCopy() *MinioGroupBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupList) DeepCopyInto(out *MinioGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupList.
func (in *MinioGroupList) DeepCopy() *MinioGroupList {
	if in == nil {
		return nil
	}
	out := new(MinioGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupSpec) DeepCopyInto(out *MinioGroupSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupSpec.
func (in *MinioGroupSpec) DeepCopy() *MinioGroupSpec {
	if in == nil {
		return nil
	}
	out := new(MinioGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupStatus) DeepCopyInto(out *MinioGroupStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioGroupSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupStatus.
func (in *MinioGroupStatus) DeepCopy() *MinioGroupStatus {
	if in == nil {
		return nil
	}
	out := new(MinioGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicy) DeepCopyInto(out *MinioPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicy.
func (in *MinioPolicy) DeepCopy() *MinioPolicy {
	if in == nil {
		return nil
	}
	out := new(MinioPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBinding) DeepCopyInto(out *MinioPolicyBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBinding.
func (in *MinioPolicyBinding) DeepCopy() *MinioPolicyBinding {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicyBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingIdentity) DeepCopyInto(out *MinioPolicyBindingIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingIdentity.
func (in *MinioPolicyBindingIdentity) DeepCopy() *MinioPolicyBindingIdentity {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingList) DeepCopyInto(out *MinioPolicyBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioPolicyBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingList.
func (in *MinioPolicyBindingList) DeepCopy() *MinioPolicyBindingList {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicyBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingSpec) DeepCopyInto(out *MinioPolicyBindingSpec) {
	*out = *in
	out.Group = in.Group
	out.TenantRef = in.TenantRef
	out.User = in.User
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingSpec.
func (in *MinioPolicyBindingSpec) DeepCopy() *MinioPolicyBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingStatus) DeepCopyInto(out *MinioPolicyBindingStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioPolicyBindingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingStatus.
func (in *MinioPolicyBindingStatus) DeepCopy() *MinioPolicyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyList) DeepCopyInto(out *MinioPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyList.
func (in *MinioPolicyList) DeepCopy() *MinioPolicyList {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicySpec) DeepCopyInto(out *MinioPolicySpec) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]MinioPolicyStatement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicySpec.
func (in *MinioPolicySpec) DeepCopy() *MinioPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MinioPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyStatement) DeepCopyInto(out *MinioPolicyStatement) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyStatement.
func (in *MinioPolicyStatement) DeepCopy() *MinioPolicyStatement {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyStatement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyStatus) DeepCopyInto(out *MinioPolicyStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyStatus.
func (in *MinioPolicyStatus) DeepCopy() *MinioPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioServiceAccount) DeepCopyInto(out *MinioServiceAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioServiceAccount.
func (in *MinioServiceAccount) DeepCopy() *MinioServiceAccount {
	if in == nil {
		return nil
	}
	out := new(MinioServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioServiceAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioServiceAccountList) DeepCopyInto(out *MinioServiceAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioServiceAccountList.
func (in *MinioServiceAccountList) DeepCopy() *MinioServiceAccountList {
	if in == nil {
		return nil
	}
	out := new(MinioServiceAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioServiceAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioServiceAccountSpec) DeepCopyInto(out *MinioServiceAccountSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioServiceAccountSpec.
func (in *MinioServiceAccountSpec) DeepCopy() *MinioServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(MinioServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioServiceAccountStatus) DeepCopyInto(out *MinioServiceAccountStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioServiceAccountSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioServiceAccountStatus.
func (in *MinioServiceAccountStatus) DeepCopy() *MinioServiceAccountStatus {
	if in == nil {
		return nil
	}
	out := new(MinioServiceAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUser) DeepCopyInto(out *MinioUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUser.
func (in *MinioUser) DeepCopy() *MinioUser {
	if in == nil {
		return nil
	}
	out := new(MinioUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUserList) DeepCopyInto(out *MinioUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUserList.
func (in *MinioUserList) DeepCopy() *MinioUserList {
	if in == nil {
		return nil
	}
	out := new(MinioUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUserSpec) DeepCopyInto(out *MinioUserSpec) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUserSpec.
func (in *MinioUserSpec) DeepCopy() *MinioUserSpec {
	if in == nil {
		return nil
	}
	out := new(MinioUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUserStatus) DeepCopyInto(out *MinioUserStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioUserSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUserStatus.
func (in *MinioUserStatus) DeepCopy() *MinioUserStatus {
	if in == nil {
		return nil
	}
	out := new(MinioUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceKeyRef) DeepCopyInto(out *ResourceKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceKeyRef.
func (in *ResourceKeyRef) DeepCopy() *ResourceKeyRef {
	if in == nil {
		return nil
	}
	out := new(ResourceKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}
