//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucket) DeepCopyInto(out *MinioBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucket.
func (in *MinioBucket) DeepCopy() *MinioBucket {
	if in == nil {
		return nil
	}
	out := new(MinioBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketList) DeepCopyInto(out *MinioBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketList.
func (in *MinioBucketList) DeepCopy() *MinioBucketList {
	if in == nil {
		return nil
	}
	out := new(MinioBucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketSpec) DeepCopyInto(out *MinioBucketSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketSpec.
func (in *MinioBucketSpec) DeepCopy() *MinioBucketSpec {
	if in == nil {
		return nil
	}
	out := new(MinioBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioBucketStatus) DeepCopyInto(out *MinioBucketStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioBucketSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioBucketStatus.
func (in *MinioBucketStatus) DeepCopy() *MinioBucketStatus {
	if in == nil {
		return nil
	}
	out := new(MinioBucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroup) DeepCopyInto(out *MinioGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroup.
func (in *MinioGroup) DeepCopy() *MinioGroup {
	if in == nil {
		return nil
	}
	out := new(MinioGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBinding) DeepCopyInto(out *MinioGroupBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBinding.
func (in *MinioGroupBinding) DeepCopy() *MinioGroupBinding {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroupBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBindingList) DeepCopyInto(out *MinioGroupBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioGroupBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBindingList.
func (in *MinioGroupBindingList) DeepCopy() *MinioGroupBindingList {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroupBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBindingSpec) DeepCopyInto(out *MinioGroupBindingSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBindingSpec.
func (in *MinioGroupBindingSpec) DeepCopy() *MinioGroupBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupBindingStatus) DeepCopyInto(out *MinioGroupBindingStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioGroupBindingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupBindingStatus.
func (in *MinioGroupBindingStatus) DeepCopy() *MinioGroupBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MinioGroupBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupList) DeepCopyInto(out *MinioGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupList.
func (in *MinioGroupList) DeepCopy() *MinioGroupList {
	if in == nil {
		return nil
	}
	out := new(MinioGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupSpec) DeepCopyInto(out *MinioGroupSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupSpec.
func (in *MinioGroupSpec) DeepCopy() *MinioGroupSpec {
	if in == nil {
		return nil
	}
	out := new(MinioGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioGroupStatus) DeepCopyInto(out *MinioGroupStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioGroupSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioGroupStatus.
func (in *MinioGroupStatus) DeepCopy() *MinioGroupStatus {
	if in == nil {
		return nil
	}
	out := new(MinioGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicy) DeepCopyInto(out *MinioPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicy.
func (in *MinioPolicy) DeepCopy() *MinioPolicy {
	if in == nil {
		return nil
	}
	out := new(MinioPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBinding) DeepCopyInto(out *MinioPolicyBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBinding.
func (in *MinioPolicyBinding) DeepCopy() *MinioPolicyBinding {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicyBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingIdentity) DeepCopyInto(out *MinioPolicyBindingIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingIdentity.
func (in *MinioPolicyBindingIdentity) DeepCopy() *MinioPolicyBindingIdentity {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingList) DeepCopyInto(out *MinioPolicyBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioPolicyBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingList.
func (in *MinioPolicyBindingList) DeepCopy() *MinioPolicyBindingList {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicyBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingSpec) DeepCopyInto(out *MinioPolicyBindingSpec) {
	*out = *in
	out.Group = in.Group
	out.TenantRef = in.TenantRef
	out.User = in.User
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingSpec.
func (in *MinioPolicyBindingSpec) DeepCopy() *MinioPolicyBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyBindingStatus) DeepCopyInto(out *MinioPolicyBindingStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioPolicyBindingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyBindingStatus.
func (in *MinioPolicyBindingStatus) DeepCopy() *MinioPolicyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyList) DeepCopyInto(out *MinioPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyList.
func (in *MinioPolicyList) DeepCopy() *MinioPolicyList {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicySpec) DeepCopyInto(out *MinioPolicySpec) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]MinioPolicyStatement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TenantRef = in.TenantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicySpec.
func (in *MinioPolicySpec) DeepCopy() *MinioPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MinioPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyStatement) DeepCopyInto(out *MinioPolicyStatement) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyStatement.
func (in *MinioPolicyStatement) DeepCopy() *MinioPolicyStatement {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyStatement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioPolicyStatus) DeepCopyInto(out *MinioPolicyStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioPolicyStatus.
func (in *MinioPolicyStatus) DeepCopy() *MinioPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MinioPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUser) DeepCopyInto(out *MinioUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUser.
func (in *MinioUser) DeepCopy() *MinioUser {
	if in == nil {
		return nil
	}
	out := new(MinioUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUserList) DeepCopyInto(out *MinioUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinioUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUserList.
func (in *MinioUserList) DeepCopy() *MinioUserList {
	if in == nil {
		return nil
	}
	out := new(MinioUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUserSpec) DeepCopyInto(out *MinioUserSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUserSpec.
func (in *MinioUserSpec) DeepCopy() *MinioUserSpec {
	if in == nil {
		return nil
	}
	out := new(MinioUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioUserStatus) DeepCopyInto(out *MinioUserStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.CurrentSpec != nil {
		in, out := &in.CurrentSpec, &out.CurrentSpec
		*out = new(MinioUserSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioUserStatus.
func (in *MinioUserStatus) DeepCopy() *MinioUserStatus {
	if in == nil {
		return nil
	}
	out := new(MinioUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceKeyRef) DeepCopyInto(out *ResourceKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceKeyRef.
func (in *ResourceKeyRef) DeepCopy() *ResourceKeyRef {
	if in == nil {
		return nil
	}
	out := new(ResourceKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}
