// Code generated by client-gen. DO NOT EDIT.

package v1

type MinioBucketExpansion interface{}

type MinioGroupExpansion interface{}

type MinioGroupBindingExpansion interface{}

type MinioPolicyExpansion interface{}

type MinioPolicyBindingExpansion interface{}

type MinioUserExpansion interface{}
