// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	rest "k8s.io/client-go/rest"
)

type MiniooperatorextV1Interface interface {
	RESTClient() rest.Interface
	MinioBucketsGetter
	MinioGroupsGetter
	MinioGroupBindingsGetter
	MinioPoliciesGetter
	MinioPolicyBindingsGetter
	MinioUsersGetter
}

// MiniooperatorextV1Client is used to interact with features provided by the miniooperatorext group.
type MiniooperatorextV1Client struct {
	restClient rest.Interface
}

func (c *MiniooperatorextV1Client) MinioBuckets(namespace string) MinioBucketInterface {
	return newMinioBuckets(c, namespace)
}

func (c *MiniooperatorextV1Client) MinioGroups(namespace string) MinioGroupInterface {
	return newMinioGroups(c, namespace)
}

func (c *MiniooperatorextV1Client) MinioGroupBindings(namespace string) MinioGroupBindingInterface {
	return newMinioGroupBindings(c, namespace)
}

func (c *MiniooperatorextV1Client) MinioPolicies(namespace string) MinioPolicyInterface {
	return newMinioPolicies(c, namespace)
}

func (c *MiniooperatorextV1Client) MinioPolicyBindings(namespace string) MinioPolicyBindingInterface {
	return newMinioPolicyBindings(c, namespace)
}

func (c *MiniooperatorextV1Client) MinioUsers(namespace string) MinioUserInterface {
	return newMinioUsers(c, namespace)
}

// NewForConfig creates a new MiniooperatorextV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*MiniooperatorextV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new MiniooperatorextV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*MiniooperatorextV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &MiniooperatorextV1Client{client}, nil
}

// NewForConfigOrDie creates a new MiniooperatorextV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MiniooperatorextV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MiniooperatorextV1Client for the given RESTClient.
func New(c rest.Interface) *MiniooperatorextV1Client {
	return &MiniooperatorextV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MiniooperatorextV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
