// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	scheme "github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MinioPoliciesGetter has a method to return a MinioPolicyInterface.
// A group's client should implement this interface.
type MinioPoliciesGetter interface {
	MinioPolicies(namespace string) MinioPolicyInterface
}

// MinioPolicyInterface has methods to work with MinioPolicy resources.
type MinioPolicyInterface interface {
	Create(ctx context.Context, minioPolicy *v1.MinioPolicy, opts metav1.CreateOptions) (*v1.MinioPolicy, error)
	Update(ctx context.Context, minioPolicy *v1.MinioPolicy, opts metav1.UpdateOptions) (*v1.MinioPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, minioPolicy *v1.MinioPolicy, opts metav1.UpdateOptions) (*v1.MinioPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MinioPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MinioPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioPolicy, err error)
	MinioPolicyExpansion
}

// minioPolicies implements MinioPolicyInterface
type minioPolicies struct {
	*gentype.ClientWithList[*v1.MinioPolicy, *v1.MinioPolicyList]
}

// newMinioPolicies returns a MinioPolicies
func newMinioPolicies(c *MiniooperatorextV1Client, namespace string) *minioPolicies {
	return &minioPolicies{
		gentype.NewClientWithList[*v1.MinioPolicy, *v1.MinioPolicyList](
			"miniopolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.MinioPolicy { return &v1.MinioPolicy{} },
			func() *v1.MinioPolicyList { return &v1.MinioPolicyList{} }),
	}
}
