// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	scheme "github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MinioGroupsGetter has a method to return a MinioGroupInterface.
// A group's client should implement this interface.
type MinioGroupsGetter interface {
	MinioGroups(namespace string) MinioGroupInterface
}

// MinioGroupInterface has methods to work with MinioGroup resources.
type MinioGroupInterface interface {
	Create(ctx context.Context, minioGroup *v1.MinioGroup, opts metav1.CreateOptions) (*v1.MinioGroup, error)
	Update(ctx context.Context, minioGroup *v1.MinioGroup, opts metav1.UpdateOptions) (*v1.MinioGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, minioGroup *v1.MinioGroup, opts metav1.UpdateOptions) (*v1.MinioGroup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MinioGroup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MinioGroupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioGroup, err error)
	MinioGroupExpansion
}

// minioGroups implements MinioGroupInterface
type minioGroups struct {
	*gentype.ClientWithList[*v1.MinioGroup, *v1.MinioGroupList]
}

// newMinioGroups returns a MinioGroups
func newMinioGroups(c *MiniooperatorextV1Client, namespace string) *minioGroups {
	return &minioGroups{
		gentype.NewClientWithList[*v1.MinioGroup, *v1.MinioGroupList](
			"miniogroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.MinioGroup { return &v1.MinioGroup{} },
			func() *v1.MinioGroupList { return &v1.MinioGroupList{} }),
	}
}
