// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	scheme "github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MinioBucketsGetter has a method to return a MinioBucketInterface.
// A group's client should implement this interface.
type MinioBucketsGetter interface {
	MinioBuckets(namespace string) MinioBucketInterface
}

// MinioBucketInterface has methods to work with MinioBucket resources.
type MinioBucketInterface interface {
	Create(ctx context.Context, minioBucket *v1.MinioBucket, opts metav1.CreateOptions) (*v1.MinioBucket, error)
	Update(ctx context.Context, minioBucket *v1.MinioBucket, opts metav1.UpdateOptions) (*v1.MinioBucket, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, minioBucket *v1.MinioBucket, opts metav1.UpdateOptions) (*v1.MinioBucket, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MinioBucket, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MinioBucketList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioBucket, err error)
	MinioBucketExpansion
}

// minioBuckets implements MinioBucketInterface
type minioBuckets struct {
	*gentype.ClientWithList[*v1.MinioBucket, *v1.MinioBucketList]
}

// newMinioBuckets returns a MinioBuckets
func newMinioBuckets(c *MiniooperatorextV1Client, namespace string) *minioBuckets {
	return &minioBuckets{
		gentype.NewClientWithList[*v1.MinioBucket, *v1.MinioBucketList](
			"miniobuckets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.MinioBucket { return &v1.MinioBucket{} },
			func() *v1.MinioBucketList { return &v1.MinioBucketList{} }),
	}
}
