// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	scheme "github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MinioPolicyBindingsGetter has a method to return a MinioPolicyBindingInterface.
// A group's client should implement this interface.
type MinioPolicyBindingsGetter interface {
	MinioPolicyBindings(namespace string) MinioPolicyBindingInterface
}

// MinioPolicyBindingInterface has methods to work with MinioPolicyBinding resources.
type MinioPolicyBindingInterface interface {
	Create(ctx context.Context, minioPolicyBinding *v1.MinioPolicyBinding, opts metav1.CreateOptions) (*v1.MinioPolicyBinding, error)
	Update(ctx context.Context, minioPolicyBinding *v1.MinioPolicyBinding, opts metav1.UpdateOptions) (*v1.MinioPolicyBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, minioPolicyBinding *v1.MinioPolicyBinding, opts metav1.UpdateOptions) (*v1.MinioPolicyBinding, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MinioPolicyBinding, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MinioPolicyBindingList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioPolicyBinding, err error)
	MinioPolicyBindingExpansion
}

// minioPolicyBindings implements MinioPolicyBindingInterface
type minioPolicyBindings struct {
	*gentype.ClientWithList[*v1.MinioPolicyBinding, *v1.MinioPolicyBindingList]
}

// newMinioPolicyBindings returns a MinioPolicyBindings
func newMinioPolicyBindings(c *MiniooperatorextV1Client, namespace string) *minioPolicyBindings {
	return &minioPolicyBindings{
		gentype.NewClientWithList[*v1.MinioPolicyBinding, *v1.MinioPolicyBindingList](
			"miniopolicybindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.MinioPolicyBinding { return &v1.MinioPolicyBinding{} },
			func() *v1.MinioPolicyBindingList { return &v1.MinioPolicyBindingList{} }),
	}
}
