// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	scheme "github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MinioGroupBindingsGetter has a method to return a MinioGroupBindingInterface.
// A group's client should implement this interface.
type MinioGroupBindingsGetter interface {
	MinioGroupBindings(namespace string) MinioGroupBindingInterface
}

// MinioGroupBindingInterface has methods to work with MinioGroupBinding resources.
type MinioGroupBindingInterface interface {
	Create(ctx context.Context, minioGroupBinding *v1.MinioGroupBinding, opts metav1.CreateOptions) (*v1.MinioGroupBinding, error)
	Update(ctx context.Context, minioGroupBinding *v1.MinioGroupBinding, opts metav1.UpdateOptions) (*v1.MinioGroupBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, minioGroupBinding *v1.MinioGroupBinding, opts metav1.UpdateOptions) (*v1.MinioGroupBinding, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MinioGroupBinding, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MinioGroupBindingList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioGroupBinding, err error)
	MinioGroupBindingExpansion
}

// minioGroupBindings implements MinioGroupBindingInterface
type minioGroupBindings struct {
	*gentype.ClientWithList[*v1.MinioGroupBinding, *v1.MinioGroupBindingList]
}

// newMinioGroupBindings returns a MinioGroupBindings
func newMinioGroupBindings(c *MiniooperatorextV1Client, namespace string) *minioGroupBindings {
	return &minioGroupBindings{
		gentype.NewClientWithList[*v1.MinioGroupBinding, *v1.MinioGroupBindingList](
			"miniogroupbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.MinioGroupBinding { return &v1.MinioGroupBinding{} },
			func() *v1.MinioGroupBindingList { return &v1.MinioGroupBindingList{} }),
	}
}
