// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	scheme "github.com/benfiola/minio-operator-ext/internal/client/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MinioUsersGetter has a method to return a MinioUserInterface.
// A group's client should implement this interface.
type MinioUsersGetter interface {
	MinioUsers(namespace string) MinioUserInterface
}

// MinioUserInterface has methods to work with MinioUser resources.
type MinioUserInterface interface {
	Create(ctx context.Context, minioUser *v1.MinioUser, opts metav1.CreateOptions) (*v1.MinioUser, error)
	Update(ctx context.Context, minioUser *v1.MinioUser, opts metav1.UpdateOptions) (*v1.MinioUser, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, minioUser *v1.MinioUser, opts metav1.UpdateOptions) (*v1.MinioUser, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MinioUser, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MinioUserList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioUser, err error)
	MinioUserExpansion
}

// minioUsers implements MinioUserInterface
type minioUsers struct {
	*gentype.ClientWithList[*v1.MinioUser, *v1.MinioUserList]
}

// newMinioUsers returns a MinioUsers
func newMinioUsers(c *MiniooperatorextV1Client, namespace string) *minioUsers {
	return &minioUsers{
		gentype.NewClientWithList[*v1.MinioUser, *v1.MinioUserList](
			"miniousers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.MinioUser { return &v1.MinioUser{} },
			func() *v1.MinioUserList { return &v1.MinioUserList{} }),
	}
}
