{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.clusterRoleName" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
  - apiGroups:
      - bfiola.dev
    resources:
      - miniobuckets
      - miniogroupbindings
      - miniogroups
      - miniopolicies
      - miniopolicybindings
      - miniousers
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - minio.min.io
    resources:
      - tenants
    verbs:
      - get
{{- end }}
