apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniobuckets.bfiola.dev
spec:
  group: bfiola.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                tenantRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
            status:
              type: object
              properties:
                currentSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Tenant Namespace
          type: string
          description: Tenant Namespace
          jsonPath: .status.currentSpec.tenantRef.namespace
        - name: Tenant Name
          type: string
          description: Tenant Name
          jsonPath: .status.currentSpec.tenantRef.name
        - name: Name
          type: string
          description: Name
          jsonPath: .status.currentSpec.name
  scope: Namespaced
  names:
    plural: miniobuckets
    singular: miniobucket
    kind: MinioBucket
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniousers.bfiola.dev
spec:
  group: bfiola.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                accessKey:
                  type: string
                secretKeyRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                    key:
                      type: string
                tenantRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
            status:
              type: object
              properties:
                currentSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Tenant Namespace
          type: string
          description: Tenant Namespace
          jsonPath: .status.currentSpec.tenantRef.namespace
        - name: Tenant Name
          type: string
          description: Tenant Name
          jsonPath: .status.currentSpec.tenantRef.name
        - name: Access Key
          type: string
          description: Access Key
          jsonPath: .status.currentSpec.accessKey
  scope: Namespaced
  names:
    plural: miniousers
    singular: miniouser
    kind: MinioUser
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniopolicies.bfiola.dev
spec:
  group: bfiola.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                tenantRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                version:
                  type: string
                  default: "2012-10-17"
                statement:
                  type: array
                  items:
                    type: object
                    properties:
                      action:
                        type: array
                        items:
                          type: string
                      resource:
                        type: array
                        items:
                          type: string
                      effect:
                        type: string
            status:
              type: object
              properties:
                currentSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Tenant Namespace
          type: string
          description: Tenant Namespace
          jsonPath: .status.currentSpec.tenantRef.namespace
        - name: Tenant Name
          type: string
          description: Tenant Name
          jsonPath: .status.currentSpec.tenantRef.name
        - name: Name
          type: string
          description: Name
          jsonPath: .status.currentSpec.name
  scope: Namespaced
  names:
    plural: miniopolicies
    singular: miniopolicy
    kind: MinioPolicy
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniopolicybindings.bfiola.dev
spec:
  group: bfiola.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                policy:
                  type: string
                user:
                  type: string
                group:
                  type: string
            status:
              type: object
              properties:
                currentSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Tenant Namespace
          type: string
          description: Tenant Namespace
          jsonPath: .status.currentSpec.tenantRef.namespace
        - name: Tenant Name
          type: string
          description: Tenant Name
          jsonPath: .status.currentSpec.tenantRef.name
        - name: Policy
          type: string
          description: Policy
          jsonPath: .status.currentSpec.policy
        - name: User
          type: string
          description: User
          jsonPath: .status.currentSpec.user
  scope: Namespaced
  names:
    plural: miniopolicybindings
    singular: miniopolicybinding
    kind: MinioPolicyBinding
