---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator-ext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-operator-ext
rules:
  - apiGroups:
      - minio.min.io
    resources:
      - tenants
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
  - apiGroups:
      - bfiola.dev
    resources:
      - miniousers
      - miniobuckets
      - miniogroups
      - miniogroupbindings
      - miniopolicies
      - miniopolicybindings
    verbs:
      - get
      - watch
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-operator-ext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-ext
subjects:
  - kind: ServiceAccount
    name: minio-operator-ext
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-operator-ext
  template:
    metadata:
      labels:
        app: minio-operator-ext
    spec:
      containers:
        - args:
            - run
          image: docker.io/benfiola/minio-operator-ext:latest
          name: operator
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
      serviceAccountName: minio-operator-ext
