apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: test
spec:
  name: test
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: v1
kind: Secret
metadata:
  name: user
stringData:
  secretKey: password
---
apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: test
spec:
  accessKey: test
  secretKeyRef:
    name: user
    key: secretKey
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: test
spec:
  name: test
  statement:
    - effect: "Allow"
      action:
        - "s3:AbortMultipartUpload"
        - "s3:DeleteObject"
        - "s3:ListMultipartUploadParts"
        - "s3:PutObject"
        - "s3:GetObject"
      resource:
        - "arn:aws:s3:::test/*"
    - effect: "Allow"
      action:
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
      resource:
        - "arn:aws:s3:::test"
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: test
spec:
  policy: test
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user: test
