apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: bucket
spec:
  deletionPolicy: IfEmpty
  name: bucket
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: v1
kind: Secret
metadata:
  name: builtin-user
stringData:
  secretKey: password
---
apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: builtin-user
spec:
  accessKey: builtin-user
  secretKeyRef:
    name: builtin-user
    key: secretKey
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioGroup
metadata:
  name: builtin-group
spec:
  name: builtin-group
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioGroupBinding
metadata:
  name: builtin-user-to-builtin-group
spec:
  group: builtin-group
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user: builtin-user
---
apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: policy
spec:
  name: policy
  statement:
    - effect: "Allow"
      action:
        - "s3:AbortMultipartUpload"
        - "s3:DeleteObject"
        - "s3:ListMultipartUploadParts"
        - "s3:PutObject"
        - "s3:GetObject"
      resource:
        - "arn:aws:s3:::bucket/*"
    - effect: "Allow"
      action:
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
      resource:
        - "arn:aws:s3:::bucket"
  tenantRef:
    namespace: minio-tenant
    name: myminio
  version: "2012-10-17"
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: builtin-user-to-policy
spec:
  policy: policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: builtin-user
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: builtin-group-to-policy
spec:
  group:
    builtin: builtin-group
  policy: policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: ldap-user-to-policy
spec:
  policy: policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    ldap: ldap-user1
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: ldap-group-to-policy
spec:
  group:
    ldap: "cn=ldap-group,ou=users,dc=example,dc=org"
  policy: policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
