apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: bucket
spec:
  name: bucket
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: v1
kind: Secret
metadata:
  name: user
stringData:
  secretKey: password
---
apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: user
spec:
  accessKey: user
  secretKeyRef:
    name: user
    key: secretKey
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioGroup
metadata:
  name: group
spec:
  name: group
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioGroupBinding
metadata:
  name: user-to-group
spec:
  group: group
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user: user
---
apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: policy
spec:
  name: policy
  statement:
    - effect: "Allow"
      action:
        - "s3:AbortMultipartUpload"
        - "s3:DeleteObject"
        - "s3:ListMultipartUploadParts"
        - "s3:PutObject"
        - "s3:GetObject"
      resource:
        - "arn:aws:s3:::bucket/*"
    - effect: "Allow"
      action:
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
      resource:
        - "arn:aws:s3:::bucket"
  tenantRef:
    namespace: minio-tenant
    name: myminio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: user-to-policy
spec:
  policy: policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user: user
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: group-to-policy
spec:
  group: group
  policy: policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
