// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=miniooperatorext, Version=v1
	case v1.SchemeGroupVersion.WithResource("miniobuckets"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Miniooperatorext().V1().MinioBuckets().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("miniogroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Miniooperatorext().V1().MinioGroups().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("miniogroupbindings"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Miniooperatorext().V1().MinioGroupBindings().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("miniopolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Miniooperatorext().V1().MinioPolicies().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("miniopolicybindings"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Miniooperatorext().V1().MinioPolicyBindings().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("miniousers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Miniooperatorext().V1().MinioUsers().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
