// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinioGroups implements MinioGroupInterface
type FakeMinioGroups struct {
	Fake *FakeMiniooperatorextV1
	ns   string
}

var miniogroupsResource = v1.SchemeGroupVersion.WithResource("miniogroups")

var miniogroupsKind = v1.SchemeGroupVersion.WithKind("MinioGroup")

// Get takes name of the minioGroup, and returns the corresponding minioGroup object, and an error if there is any.
func (c *FakeMinioGroups) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MinioGroup, err error) {
	emptyResult := &v1.MinioGroup{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(miniogroupsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroup), err
}

// List takes label and field selectors, and returns the list of MinioGroups that match those selectors.
func (c *FakeMinioGroups) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MinioGroupList, err error) {
	emptyResult := &v1.MinioGroupList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(miniogroupsResource, miniogroupsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MinioGroupList{ListMeta: obj.(*v1.MinioGroupList).ListMeta}
	for _, item := range obj.(*v1.MinioGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minioGroups.
func (c *FakeMinioGroups) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(miniogroupsResource, c.ns, opts))

}

// Create takes the representation of a minioGroup and creates it.  Returns the server's representation of the minioGroup, and an error, if there is any.
func (c *FakeMinioGroups) Create(ctx context.Context, minioGroup *v1.MinioGroup, opts metav1.CreateOptions) (result *v1.MinioGroup, err error) {
	emptyResult := &v1.MinioGroup{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(miniogroupsResource, c.ns, minioGroup, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroup), err
}

// Update takes the representation of a minioGroup and updates it. Returns the server's representation of the minioGroup, and an error, if there is any.
func (c *FakeMinioGroups) Update(ctx context.Context, minioGroup *v1.MinioGroup, opts metav1.UpdateOptions) (result *v1.MinioGroup, err error) {
	emptyResult := &v1.MinioGroup{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(miniogroupsResource, c.ns, minioGroup, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinioGroups) UpdateStatus(ctx context.Context, minioGroup *v1.MinioGroup, opts metav1.UpdateOptions) (result *v1.MinioGroup, err error) {
	emptyResult := &v1.MinioGroup{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(miniogroupsResource, "status", c.ns, minioGroup, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroup), err
}

// Delete takes name of the minioGroup and deletes it. Returns an error if one occurs.
func (c *FakeMinioGroups) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(miniogroupsResource, c.ns, name, opts), &v1.MinioGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinioGroups) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(miniogroupsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MinioGroupList{})
	return err
}

// Patch applies the patch and returns the patched minioGroup.
func (c *FakeMinioGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioGroup, err error) {
	emptyResult := &v1.MinioGroup{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(miniogroupsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroup), err
}
