// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinioPolicies implements MinioPolicyInterface
type FakeMinioPolicies struct {
	Fake *FakeMiniooperatorextV1
	ns   string
}

var miniopoliciesResource = v1.SchemeGroupVersion.WithResource("miniopolicies")

var miniopoliciesKind = v1.SchemeGroupVersion.WithKind("MinioPolicy")

// Get takes name of the minioPolicy, and returns the corresponding minioPolicy object, and an error if there is any.
func (c *FakeMinioPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MinioPolicy, err error) {
	emptyResult := &v1.MinioPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(miniopoliciesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicy), err
}

// List takes label and field selectors, and returns the list of MinioPolicies that match those selectors.
func (c *FakeMinioPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MinioPolicyList, err error) {
	emptyResult := &v1.MinioPolicyList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(miniopoliciesResource, miniopoliciesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MinioPolicyList{ListMeta: obj.(*v1.MinioPolicyList).ListMeta}
	for _, item := range obj.(*v1.MinioPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minioPolicies.
func (c *FakeMinioPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(miniopoliciesResource, c.ns, opts))

}

// Create takes the representation of a minioPolicy and creates it.  Returns the server's representation of the minioPolicy, and an error, if there is any.
func (c *FakeMinioPolicies) Create(ctx context.Context, minioPolicy *v1.MinioPolicy, opts metav1.CreateOptions) (result *v1.MinioPolicy, err error) {
	emptyResult := &v1.MinioPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(miniopoliciesResource, c.ns, minioPolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicy), err
}

// Update takes the representation of a minioPolicy and updates it. Returns the server's representation of the minioPolicy, and an error, if there is any.
func (c *FakeMinioPolicies) Update(ctx context.Context, minioPolicy *v1.MinioPolicy, opts metav1.UpdateOptions) (result *v1.MinioPolicy, err error) {
	emptyResult := &v1.MinioPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(miniopoliciesResource, c.ns, minioPolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinioPolicies) UpdateStatus(ctx context.Context, minioPolicy *v1.MinioPolicy, opts metav1.UpdateOptions) (result *v1.MinioPolicy, err error) {
	emptyResult := &v1.MinioPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(miniopoliciesResource, "status", c.ns, minioPolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicy), err
}

// Delete takes name of the minioPolicy and deletes it. Returns an error if one occurs.
func (c *FakeMinioPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(miniopoliciesResource, c.ns, name, opts), &v1.MinioPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinioPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(miniopoliciesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MinioPolicyList{})
	return err
}

// Patch applies the patch and returns the patched minioPolicy.
func (c *FakeMinioPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioPolicy, err error) {
	emptyResult := &v1.MinioPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(miniopoliciesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicy), err
}
