// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinioPolicyBindings implements MinioPolicyBindingInterface
type FakeMinioPolicyBindings struct {
	Fake *FakeMiniooperatorextV1
	ns   string
}

var miniopolicybindingsResource = v1.SchemeGroupVersion.WithResource("miniopolicybindings")

var miniopolicybindingsKind = v1.SchemeGroupVersion.WithKind("MinioPolicyBinding")

// Get takes name of the minioPolicyBinding, and returns the corresponding minioPolicyBinding object, and an error if there is any.
func (c *FakeMinioPolicyBindings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MinioPolicyBinding, err error) {
	emptyResult := &v1.MinioPolicyBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(miniopolicybindingsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicyBinding), err
}

// List takes label and field selectors, and returns the list of MinioPolicyBindings that match those selectors.
func (c *FakeMinioPolicyBindings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MinioPolicyBindingList, err error) {
	emptyResult := &v1.MinioPolicyBindingList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(miniopolicybindingsResource, miniopolicybindingsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MinioPolicyBindingList{ListMeta: obj.(*v1.MinioPolicyBindingList).ListMeta}
	for _, item := range obj.(*v1.MinioPolicyBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minioPolicyBindings.
func (c *FakeMinioPolicyBindings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(miniopolicybindingsResource, c.ns, opts))

}

// Create takes the representation of a minioPolicyBinding and creates it.  Returns the server's representation of the minioPolicyBinding, and an error, if there is any.
func (c *FakeMinioPolicyBindings) Create(ctx context.Context, minioPolicyBinding *v1.MinioPolicyBinding, opts metav1.CreateOptions) (result *v1.MinioPolicyBinding, err error) {
	emptyResult := &v1.MinioPolicyBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(miniopolicybindingsResource, c.ns, minioPolicyBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicyBinding), err
}

// Update takes the representation of a minioPolicyBinding and updates it. Returns the server's representation of the minioPolicyBinding, and an error, if there is any.
func (c *FakeMinioPolicyBindings) Update(ctx context.Context, minioPolicyBinding *v1.MinioPolicyBinding, opts metav1.UpdateOptions) (result *v1.MinioPolicyBinding, err error) {
	emptyResult := &v1.MinioPolicyBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(miniopolicybindingsResource, c.ns, minioPolicyBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicyBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinioPolicyBindings) UpdateStatus(ctx context.Context, minioPolicyBinding *v1.MinioPolicyBinding, opts metav1.UpdateOptions) (result *v1.MinioPolicyBinding, err error) {
	emptyResult := &v1.MinioPolicyBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(miniopolicybindingsResource, "status", c.ns, minioPolicyBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicyBinding), err
}

// Delete takes name of the minioPolicyBinding and deletes it. Returns an error if one occurs.
func (c *FakeMinioPolicyBindings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(miniopolicybindingsResource, c.ns, name, opts), &v1.MinioPolicyBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinioPolicyBindings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(miniopolicybindingsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MinioPolicyBindingList{})
	return err
}

// Patch applies the patch and returns the patched minioPolicyBinding.
func (c *FakeMinioPolicyBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioPolicyBinding, err error) {
	emptyResult := &v1.MinioPolicyBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(miniopolicybindingsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioPolicyBinding), err
}
