// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinioBuckets implements MinioBucketInterface
type FakeMinioBuckets struct {
	Fake *FakeMiniooperatorextV1
	ns   string
}

var miniobucketsResource = v1.SchemeGroupVersion.WithResource("miniobuckets")

var miniobucketsKind = v1.SchemeGroupVersion.WithKind("MinioBucket")

// Get takes name of the minioBucket, and returns the corresponding minioBucket object, and an error if there is any.
func (c *FakeMinioBuckets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MinioBucket, err error) {
	emptyResult := &v1.MinioBucket{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(miniobucketsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioBucket), err
}

// List takes label and field selectors, and returns the list of MinioBuckets that match those selectors.
func (c *FakeMinioBuckets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MinioBucketList, err error) {
	emptyResult := &v1.MinioBucketList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(miniobucketsResource, miniobucketsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MinioBucketList{ListMeta: obj.(*v1.MinioBucketList).ListMeta}
	for _, item := range obj.(*v1.MinioBucketList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minioBuckets.
func (c *FakeMinioBuckets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(miniobucketsResource, c.ns, opts))

}

// Create takes the representation of a minioBucket and creates it.  Returns the server's representation of the minioBucket, and an error, if there is any.
func (c *FakeMinioBuckets) Create(ctx context.Context, minioBucket *v1.MinioBucket, opts metav1.CreateOptions) (result *v1.MinioBucket, err error) {
	emptyResult := &v1.MinioBucket{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(miniobucketsResource, c.ns, minioBucket, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioBucket), err
}

// Update takes the representation of a minioBucket and updates it. Returns the server's representation of the minioBucket, and an error, if there is any.
func (c *FakeMinioBuckets) Update(ctx context.Context, minioBucket *v1.MinioBucket, opts metav1.UpdateOptions) (result *v1.MinioBucket, err error) {
	emptyResult := &v1.MinioBucket{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(miniobucketsResource, c.ns, minioBucket, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioBucket), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinioBuckets) UpdateStatus(ctx context.Context, minioBucket *v1.MinioBucket, opts metav1.UpdateOptions) (result *v1.MinioBucket, err error) {
	emptyResult := &v1.MinioBucket{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(miniobucketsResource, "status", c.ns, minioBucket, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioBucket), err
}

// Delete takes name of the minioBucket and deletes it. Returns an error if one occurs.
func (c *FakeMinioBuckets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(miniobucketsResource, c.ns, name, opts), &v1.MinioBucket{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinioBuckets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(miniobucketsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MinioBucketList{})
	return err
}

// Patch applies the patch and returns the patched minioBucket.
func (c *FakeMinioBuckets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioBucket, err error) {
	emptyResult := &v1.MinioBucket{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(miniobucketsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioBucket), err
}
