// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinioUsers implements MinioUserInterface
type FakeMinioUsers struct {
	Fake *FakeMiniooperatorextV1
	ns   string
}

var miniousersResource = v1.SchemeGroupVersion.WithResource("miniousers")

var miniousersKind = v1.SchemeGroupVersion.WithKind("MinioUser")

// Get takes name of the minioUser, and returns the corresponding minioUser object, and an error if there is any.
func (c *FakeMinioUsers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MinioUser, err error) {
	emptyResult := &v1.MinioUser{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(miniousersResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioUser), err
}

// List takes label and field selectors, and returns the list of MinioUsers that match those selectors.
func (c *FakeMinioUsers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MinioUserList, err error) {
	emptyResult := &v1.MinioUserList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(miniousersResource, miniousersKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MinioUserList{ListMeta: obj.(*v1.MinioUserList).ListMeta}
	for _, item := range obj.(*v1.MinioUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minioUsers.
func (c *FakeMinioUsers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(miniousersResource, c.ns, opts))

}

// Create takes the representation of a minioUser and creates it.  Returns the server's representation of the minioUser, and an error, if there is any.
func (c *FakeMinioUsers) Create(ctx context.Context, minioUser *v1.MinioUser, opts metav1.CreateOptions) (result *v1.MinioUser, err error) {
	emptyResult := &v1.MinioUser{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(miniousersResource, c.ns, minioUser, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioUser), err
}

// Update takes the representation of a minioUser and updates it. Returns the server's representation of the minioUser, and an error, if there is any.
func (c *FakeMinioUsers) Update(ctx context.Context, minioUser *v1.MinioUser, opts metav1.UpdateOptions) (result *v1.MinioUser, err error) {
	emptyResult := &v1.MinioUser{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(miniousersResource, c.ns, minioUser, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinioUsers) UpdateStatus(ctx context.Context, minioUser *v1.MinioUser, opts metav1.UpdateOptions) (result *v1.MinioUser, err error) {
	emptyResult := &v1.MinioUser{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(miniousersResource, "status", c.ns, minioUser, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioUser), err
}

// Delete takes name of the minioUser and deletes it. Returns an error if one occurs.
func (c *FakeMinioUsers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(miniousersResource, c.ns, name, opts), &v1.MinioUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinioUsers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(miniousersResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MinioUserList{})
	return err
}

// Patch applies the patch and returns the patched minioUser.
func (c *FakeMinioUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioUser, err error) {
	emptyResult := &v1.MinioUser{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(miniousersResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioUser), err
}
