// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinioGroupBindings implements MinioGroupBindingInterface
type FakeMinioGroupBindings struct {
	Fake *FakeMiniooperatorextV1
	ns   string
}

var miniogroupbindingsResource = v1.SchemeGroupVersion.WithResource("miniogroupbindings")

var miniogroupbindingsKind = v1.SchemeGroupVersion.WithKind("MinioGroupBinding")

// Get takes name of the minioGroupBinding, and returns the corresponding minioGroupBinding object, and an error if there is any.
func (c *FakeMinioGroupBindings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MinioGroupBinding, err error) {
	emptyResult := &v1.MinioGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(miniogroupbindingsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroupBinding), err
}

// List takes label and field selectors, and returns the list of MinioGroupBindings that match those selectors.
func (c *FakeMinioGroupBindings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MinioGroupBindingList, err error) {
	emptyResult := &v1.MinioGroupBindingList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(miniogroupbindingsResource, miniogroupbindingsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MinioGroupBindingList{ListMeta: obj.(*v1.MinioGroupBindingList).ListMeta}
	for _, item := range obj.(*v1.MinioGroupBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minioGroupBindings.
func (c *FakeMinioGroupBindings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(miniogroupbindingsResource, c.ns, opts))

}

// Create takes the representation of a minioGroupBinding and creates it.  Returns the server's representation of the minioGroupBinding, and an error, if there is any.
func (c *FakeMinioGroupBindings) Create(ctx context.Context, minioGroupBinding *v1.MinioGroupBinding, opts metav1.CreateOptions) (result *v1.MinioGroupBinding, err error) {
	emptyResult := &v1.MinioGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(miniogroupbindingsResource, c.ns, minioGroupBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroupBinding), err
}

// Update takes the representation of a minioGroupBinding and updates it. Returns the server's representation of the minioGroupBinding, and an error, if there is any.
func (c *FakeMinioGroupBindings) Update(ctx context.Context, minioGroupBinding *v1.MinioGroupBinding, opts metav1.UpdateOptions) (result *v1.MinioGroupBinding, err error) {
	emptyResult := &v1.MinioGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(miniogroupbindingsResource, c.ns, minioGroupBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroupBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinioGroupBindings) UpdateStatus(ctx context.Context, minioGroupBinding *v1.MinioGroupBinding, opts metav1.UpdateOptions) (result *v1.MinioGroupBinding, err error) {
	emptyResult := &v1.MinioGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(miniogroupbindingsResource, "status", c.ns, minioGroupBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroupBinding), err
}

// Delete takes name of the minioGroupBinding and deletes it. Returns an error if one occurs.
func (c *FakeMinioGroupBindings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(miniogroupbindingsResource, c.ns, name, opts), &v1.MinioGroupBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinioGroupBindings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(miniogroupbindingsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MinioGroupBindingList{})
	return err
}

// Patch applies the patch and returns the patched minioGroupBinding.
func (c *FakeMinioGroupBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MinioGroupBinding, err error) {
	emptyResult := &v1.MinioGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(miniogroupbindingsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.MinioGroupBinding), err
}
