// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/client/clientset/typed/miniooperatorext/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMiniooperatorextV1 struct {
	*testing.Fake
}

func (c *FakeMiniooperatorextV1) MinioBuckets(namespace string) v1.MinioBucketInterface {
	return &FakeMinioBuckets{c, namespace}
}

func (c *FakeMiniooperatorextV1) MinioGroups(namespace string) v1.MinioGroupInterface {
	return &FakeMinioGroups{c, namespace}
}

func (c *FakeMiniooperatorextV1) MinioGroupBindings(namespace string) v1.MinioGroupBindingInterface {
	return &FakeMinioGroupBindings{c, namespace}
}

func (c *FakeMiniooperatorextV1) MinioPolicies(namespace string) v1.MinioPolicyInterface {
	return &FakeMinioPolicies{c, namespace}
}

func (c *FakeMiniooperatorextV1) MinioPolicyBindings(namespace string) v1.MinioPolicyBindingInterface {
	return &FakeMinioPolicyBindings{c, namespace}
}

func (c *FakeMiniooperatorextV1) MinioUsers(namespace string) v1.MinioUserInterface {
	return &FakeMinioUsers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMiniooperatorextV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
