// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/benfiola/minio-operator-ext/internal/client/informer/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MinioBuckets returns a MinioBucketInformer.
	MinioBuckets() MinioBucketInformer
	// MinioGroups returns a MinioGroupInformer.
	MinioGroups() MinioGroupInformer
	// MinioGroupBindings returns a MinioGroupBindingInformer.
	MinioGroupBindings() MinioGroupBindingInformer
	// MinioPolicies returns a MinioPolicyInformer.
	MinioPolicies() MinioPolicyInformer
	// MinioPolicyBindings returns a MinioPolicyBindingInformer.
	MinioPolicyBindings() MinioPolicyBindingInformer
	// MinioUsers returns a MinioUserInformer.
	MinioUsers() MinioUserInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MinioBuckets returns a MinioBucketInformer.
func (v *version) MinioBuckets() MinioBucketInformer {
	return &minioBucketInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MinioGroups returns a MinioGroupInformer.
func (v *version) MinioGroups() MinioGroupInformer {
	return &minioGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MinioGroupBindings returns a MinioGroupBindingInformer.
func (v *version) MinioGroupBindings() MinioGroupBindingInformer {
	return &minioGroupBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MinioPolicies returns a MinioPolicyInformer.
func (v *version) MinioPolicies() MinioPolicyInformer {
	return &minioPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MinioPolicyBindings returns a MinioPolicyBindingInformer.
func (v *version) MinioPolicyBindings() MinioPolicyBindingInformer {
	return &minioPolicyBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MinioUsers returns a MinioUserInformer.
func (v *version) MinioUsers() MinioUserInformer {
	return &minioUserInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
