// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	miniooperatorextv1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	clientset "github.com/benfiola/minio-operator-ext/internal/client/clientset"
	internalinterfaces "github.com/benfiola/minio-operator-ext/internal/client/informer/externalversions/internalinterfaces"
	v1 "github.com/benfiola/minio-operator-ext/internal/client/lister/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MinioPolicyInformer provides access to a shared informer and lister for
// MinioPolicies.
type MinioPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MinioPolicyLister
}

type minioPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMinioPolicyInformer constructs a new informer for MinioPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMinioPolicyInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMinioPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMinioPolicyInformer constructs a new informer for MinioPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMinioPolicyInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorextV1().MinioPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorextV1().MinioPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&miniooperatorextv1.MinioPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *minioPolicyInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMinioPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *minioPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&miniooperatorextv1.MinioPolicy{}, f.defaultInformer)
}

func (f *minioPolicyInformer) Lister() v1.MinioPolicyLister {
	return v1.NewMinioPolicyLister(f.Informer().GetIndexer())
}
