// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	miniooperatorextv1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	clientset "github.com/benfiola/minio-operator-ext/internal/client/clientset"
	internalinterfaces "github.com/benfiola/minio-operator-ext/internal/client/informer/externalversions/internalinterfaces"
	v1 "github.com/benfiola/minio-operator-ext/internal/client/lister/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MinioPolicyBindingInformer provides access to a shared informer and lister for
// MinioPolicyBindings.
type MinioPolicyBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MinioPolicyBindingLister
}

type minioPolicyBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMinioPolicyBindingInformer constructs a new informer for MinioPolicyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMinioPolicyBindingInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMinioPolicyBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMinioPolicyBindingInformer constructs a new informer for MinioPolicyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMinioPolicyBindingInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorextV1().MinioPolicyBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorextV1().MinioPolicyBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&miniooperatorextv1.MinioPolicyBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *minioPolicyBindingInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMinioPolicyBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *minioPolicyBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&miniooperatorextv1.MinioPolicyBinding{}, f.defaultInformer)
}

func (f *minioPolicyBindingInformer) Lister() v1.MinioPolicyBindingLister {
	return v1.NewMinioPolicyBindingLister(f.Informer().GetIndexer())
}
