// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	miniooperatorextv1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	clientset "github.com/benfiola/minio-operator-ext/internal/client/clientset"
	internalinterfaces "github.com/benfiola/minio-operator-ext/internal/client/informer/externalversions/internalinterfaces"
	v1 "github.com/benfiola/minio-operator-ext/internal/client/lister/miniooperatorext/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MinioGroupBindingInformer provides access to a shared informer and lister for
// MinioGroupBindings.
type MinioGroupBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MinioGroupBindingLister
}

type minioGroupBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMinioGroupBindingInformer constructs a new informer for MinioGroupBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMinioGroupBindingInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMinioGroupBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMinioGroupBindingInformer constructs a new informer for MinioGroupBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMinioGroupBindingInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorextV1().MinioGroupBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorextV1().MinioGroupBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&miniooperatorextv1.MinioGroupBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *minioGroupBindingInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMinioGroupBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *minioGroupBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&miniooperatorextv1.MinioGroupBinding{}, f.defaultInformer)
}

func (f *minioGroupBindingInformer) Lister() v1.MinioGroupBindingLister {
	return v1.NewMinioGroupBindingLister(f.Informer().GetIndexer())
}
