// Code generated by lister-gen. DO NOT EDIT.

package v1

// MinioBucketListerExpansion allows custom methods to be added to
// MinioBucketLister.
type MinioBucketListerExpansion interface{}

// MinioBucketNamespaceListerExpansion allows custom methods to be added to
// MinioBucketNamespaceLister.
type MinioBucketNamespaceListerExpansion interface{}

// MinioGroupListerExpansion allows custom methods to be added to
// MinioGroupLister.
type MinioGroupListerExpansion interface{}

// MinioGroupNamespaceListerExpansion allows custom methods to be added to
// MinioGroupNamespaceLister.
type MinioGroupNamespaceListerExpansion interface{}

// MinioGroupBindingListerExpansion allows custom methods to be added to
// MinioGroupBindingLister.
type MinioGroupBindingListerExpansion interface{}

// MinioGroupBindingNamespaceListerExpansion allows custom methods to be added to
// MinioGroupBindingNamespaceLister.
type MinioGroupBindingNamespaceListerExpansion interface{}

// MinioPolicyListerExpansion allows custom methods to be added to
// MinioPolicyLister.
type MinioPolicyListerExpansion interface{}

// MinioPolicyNamespaceListerExpansion allows custom methods to be added to
// MinioPolicyNamespaceLister.
type MinioPolicyNamespaceListerExpansion interface{}

// MinioPolicyBindingListerExpansion allows custom methods to be added to
// MinioPolicyBindingLister.
type MinioPolicyBindingListerExpansion interface{}

// MinioPolicyBindingNamespaceListerExpansion allows custom methods to be added to
// MinioPolicyBindingNamespaceLister.
type MinioPolicyBindingNamespaceListerExpansion interface{}

// MinioUserListerExpansion allows custom methods to be added to
// MinioUserLister.
type MinioUserListerExpansion interface{}

// MinioUserNamespaceListerExpansion allows custom methods to be added to
// MinioUserNamespaceLister.
type MinioUserNamespaceListerExpansion interface{}
