// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MinioGroupBindingLister helps list MinioGroupBindings.
// All objects returned here must be treated as read-only.
type MinioGroupBindingLister interface {
	// List lists all MinioGroupBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioGroupBinding, err error)
	// MinioGroupBindings returns an object that can list and get MinioGroupBindings.
	MinioGroupBindings(namespace string) MinioGroupBindingNamespaceLister
	MinioGroupBindingListerExpansion
}

// minioGroupBindingLister implements the MinioGroupBindingLister interface.
type minioGroupBindingLister struct {
	listers.ResourceIndexer[*v1.MinioGroupBinding]
}

// NewMinioGroupBindingLister returns a new MinioGroupBindingLister.
func NewMinioGroupBindingLister(indexer cache.Indexer) MinioGroupBindingLister {
	return &minioGroupBindingLister{listers.New[*v1.MinioGroupBinding](indexer, v1.Resource("miniogroupbinding"))}
}

// MinioGroupBindings returns an object that can list and get MinioGroupBindings.
func (s *minioGroupBindingLister) MinioGroupBindings(namespace string) MinioGroupBindingNamespaceLister {
	return minioGroupBindingNamespaceLister{listers.NewNamespaced[*v1.MinioGroupBinding](s.ResourceIndexer, namespace)}
}

// MinioGroupBindingNamespaceLister helps list and get MinioGroupBindings.
// All objects returned here must be treated as read-only.
type MinioGroupBindingNamespaceLister interface {
	// List lists all MinioGroupBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioGroupBinding, err error)
	// Get retrieves the MinioGroupBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinioGroupBinding, error)
	MinioGroupBindingNamespaceListerExpansion
}

// minioGroupBindingNamespaceLister implements the MinioGroupBindingNamespaceLister
// interface.
type minioGroupBindingNamespaceLister struct {
	listers.ResourceIndexer[*v1.MinioGroupBinding]
}
