// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MinioPolicyBindingLister helps list MinioPolicyBindings.
// All objects returned here must be treated as read-only.
type MinioPolicyBindingLister interface {
	// List lists all MinioPolicyBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioPolicyBinding, err error)
	// MinioPolicyBindings returns an object that can list and get MinioPolicyBindings.
	MinioPolicyBindings(namespace string) MinioPolicyBindingNamespaceLister
	MinioPolicyBindingListerExpansion
}

// minioPolicyBindingLister implements the MinioPolicyBindingLister interface.
type minioPolicyBindingLister struct {
	listers.ResourceIndexer[*v1.MinioPolicyBinding]
}

// NewMinioPolicyBindingLister returns a new MinioPolicyBindingLister.
func NewMinioPolicyBindingLister(indexer cache.Indexer) MinioPolicyBindingLister {
	return &minioPolicyBindingLister{listers.New[*v1.MinioPolicyBinding](indexer, v1.Resource("miniopolicybinding"))}
}

// MinioPolicyBindings returns an object that can list and get MinioPolicyBindings.
func (s *minioPolicyBindingLister) MinioPolicyBindings(namespace string) MinioPolicyBindingNamespaceLister {
	return minioPolicyBindingNamespaceLister{listers.NewNamespaced[*v1.MinioPolicyBinding](s.ResourceIndexer, namespace)}
}

// MinioPolicyBindingNamespaceLister helps list and get MinioPolicyBindings.
// All objects returned here must be treated as read-only.
type MinioPolicyBindingNamespaceLister interface {
	// List lists all MinioPolicyBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioPolicyBinding, err error)
	// Get retrieves the MinioPolicyBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinioPolicyBinding, error)
	MinioPolicyBindingNamespaceListerExpansion
}

// minioPolicyBindingNamespaceLister implements the MinioPolicyBindingNamespaceLister
// interface.
type minioPolicyBindingNamespaceLister struct {
	listers.ResourceIndexer[*v1.MinioPolicyBinding]
}
