// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MinioBucketLister helps list MinioBuckets.
// All objects returned here must be treated as read-only.
type MinioBucketLister interface {
	// List lists all MinioBuckets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioBucket, err error)
	// MinioBuckets returns an object that can list and get MinioBuckets.
	MinioBuckets(namespace string) MinioBucketNamespaceLister
	MinioBucketListerExpansion
}

// minioBucketLister implements the MinioBucketLister interface.
type minioBucketLister struct {
	listers.ResourceIndexer[*v1.MinioBucket]
}

// NewMinioBucketLister returns a new MinioBucketLister.
func NewMinioBucketLister(indexer cache.Indexer) MinioBucketLister {
	return &minioBucketLister{listers.New[*v1.MinioBucket](indexer, v1.Resource("miniobucket"))}
}

// MinioBuckets returns an object that can list and get MinioBuckets.
func (s *minioBucketLister) MinioBuckets(namespace string) MinioBucketNamespaceLister {
	return minioBucketNamespaceLister{listers.NewNamespaced[*v1.MinioBucket](s.ResourceIndexer, namespace)}
}

// MinioBucketNamespaceLister helps list and get MinioBuckets.
// All objects returned here must be treated as read-only.
type MinioBucketNamespaceLister interface {
	// List lists all MinioBuckets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioBucket, err error)
	// Get retrieves the MinioBucket from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinioBucket, error)
	MinioBucketNamespaceListerExpansion
}

// minioBucketNamespaceLister implements the MinioBucketNamespaceLister
// interface.
type minioBucketNamespaceLister struct {
	listers.ResourceIndexer[*v1.MinioBucket]
}
