// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MinioGroupLister helps list MinioGroups.
// All objects returned here must be treated as read-only.
type MinioGroupLister interface {
	// List lists all MinioGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioGroup, err error)
	// MinioGroups returns an object that can list and get MinioGroups.
	MinioGroups(namespace string) MinioGroupNamespaceLister
	MinioGroupListerExpansion
}

// minioGroupLister implements the MinioGroupLister interface.
type minioGroupLister struct {
	listers.ResourceIndexer[*v1.MinioGroup]
}

// NewMinioGroupLister returns a new MinioGroupLister.
func NewMinioGroupLister(indexer cache.Indexer) MinioGroupLister {
	return &minioGroupLister{listers.New[*v1.MinioGroup](indexer, v1.Resource("miniogroup"))}
}

// MinioGroups returns an object that can list and get MinioGroups.
func (s *minioGroupLister) MinioGroups(namespace string) MinioGroupNamespaceLister {
	return minioGroupNamespaceLister{listers.NewNamespaced[*v1.MinioGroup](s.ResourceIndexer, namespace)}
}

// MinioGroupNamespaceLister helps list and get MinioGroups.
// All objects returned here must be treated as read-only.
type MinioGroupNamespaceLister interface {
	// List lists all MinioGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioGroup, err error)
	// Get retrieves the MinioGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinioGroup, error)
	MinioGroupNamespaceListerExpansion
}

// minioGroupNamespaceLister implements the MinioGroupNamespaceLister
// interface.
type minioGroupNamespaceLister struct {
	listers.ResourceIndexer[*v1.MinioGroup]
}
