// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MinioPolicyLister helps list MinioPolicies.
// All objects returned here must be treated as read-only.
type MinioPolicyLister interface {
	// List lists all MinioPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioPolicy, err error)
	// MinioPolicies returns an object that can list and get MinioPolicies.
	MinioPolicies(namespace string) MinioPolicyNamespaceLister
	MinioPolicyListerExpansion
}

// minioPolicyLister implements the MinioPolicyLister interface.
type minioPolicyLister struct {
	listers.ResourceIndexer[*v1.MinioPolicy]
}

// NewMinioPolicyLister returns a new MinioPolicyLister.
func NewMinioPolicyLister(indexer cache.Indexer) MinioPolicyLister {
	return &minioPolicyLister{listers.New[*v1.MinioPolicy](indexer, v1.Resource("miniopolicy"))}
}

// MinioPolicies returns an object that can list and get MinioPolicies.
func (s *minioPolicyLister) MinioPolicies(namespace string) MinioPolicyNamespaceLister {
	return minioPolicyNamespaceLister{listers.NewNamespaced[*v1.MinioPolicy](s.ResourceIndexer, namespace)}
}

// MinioPolicyNamespaceLister helps list and get MinioPolicies.
// All objects returned here must be treated as read-only.
type MinioPolicyNamespaceLister interface {
	// List lists all MinioPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioPolicy, err error)
	// Get retrieves the MinioPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinioPolicy, error)
	MinioPolicyNamespaceListerExpansion
}

// minioPolicyNamespaceLister implements the MinioPolicyNamespaceLister
// interface.
type minioPolicyNamespaceLister struct {
	listers.ResourceIndexer[*v1.MinioPolicy]
}
