// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/benfiola/minio-operator-ext/internal/api/miniooperatorext/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MinioUserLister helps list MinioUsers.
// All objects returned here must be treated as read-only.
type MinioUserLister interface {
	// List lists all MinioUsers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioUser, err error)
	// MinioUsers returns an object that can list and get MinioUsers.
	MinioUsers(namespace string) MinioUserNamespaceLister
	MinioUserListerExpansion
}

// minioUserLister implements the MinioUserLister interface.
type minioUserLister struct {
	listers.ResourceIndexer[*v1.MinioUser]
}

// NewMinioUserLister returns a new MinioUserLister.
func NewMinioUserLister(indexer cache.Indexer) MinioUserLister {
	return &minioUserLister{listers.New[*v1.MinioUser](indexer, v1.Resource("miniouser"))}
}

// MinioUsers returns an object that can list and get MinioUsers.
func (s *minioUserLister) MinioUsers(namespace string) MinioUserNamespaceLister {
	return minioUserNamespaceLister{listers.NewNamespaced[*v1.MinioUser](s.ResourceIndexer, namespace)}
}

// MinioUserNamespaceLister helps list and get MinioUsers.
// All objects returned here must be treated as read-only.
type MinioUserNamespaceLister interface {
	// List lists all MinioUsers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinioUser, err error)
	// Get retrieves the MinioUser from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinioUser, error)
	MinioUserNamespaceListerExpansion
}

// minioUserNamespaceLister implements the MinioUserNamespaceLister
// interface.
type minioUserNamespaceLister struct {
	listers.ResourceIndexer[*v1.MinioUser]
}
