apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - image: docker.io/bitnami/openldap:2.5
          name: openldap
          env:
            - name: LDAP_ADMIN_USERNAME
              value: ldap-admin
            - name: LDAP_ADMIN_PASSWORD
              value: ldap-admin
            - name: LDAP_USERS
              value: ldap-user1,ldap-user2
            - name: LDAP_PASSWORDS
              value: ldap-user1,ldap-user2
            - name: LDAP_GROUP
              value: ldap-group
            - name: LDAP_ROOT
              value: dc=example,dc=org
            - name: LDAP_ADMIN_DN
              value: cn=admin,dc=example,dc=org
            - name: LDAP_LOGLEVEL
              value: "1"
          ports:
            - containerPort: 1389
            - containerPort: 1636
