apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  type: LoadBalancer
  selector:
    app: openldap
  ports:
    - name: unencrypted
      protocol: TCP
      port: 389
      targetPort: 1389
    - name: encrypted
      protocol: TCP
      port: 636
      targetPort: 1389
