name: publish
on:
  push:
    branches:
      - main
      - dev
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment:
      name: docker
      url: https://hub.docker.com/repository/docker/benfiola/minio-operator-ext/general
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: run
        id: main
        run: |
          docker buildx create --platform linux/arm64,linux/amd64 --use
          pip install --no-color --progress-bar=off --editable ".[dev]"
          devtools publish-github-action docker --token "${{secrets.DOCKER_TOKEN}}"
      - name: tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.main.outputs.tag}}',
              sha: context.sha
            })
